from enum import Enum

class ALTO (Enum):
    NORMAL_ALTO = 1100

    ALTO_CONTAINER = 400

    ALTO_FRAME1 = 100
    ALTO_FRAME2 = 550
# BOTONES
    ALTO_BOTON = 60

    ALTO_BOTON_INVENTARIO= 40

    ALTO_LABEL_FLAME = 100