from enum import Enum

class ALTO (Enum):

    NORMAL_ALTO =  100

    ALTO_CONTAINER = 400

    ALTO_FRAME2 = 650
# BOTONES
    ALTO_BOTON =  240
    ALTO_BOTON_INVENTARIO= 50
    ALTO_BOTON_VENTAS = 50
# LABEL FRAME
    ALTO_LABEL_FLAME = 550
    ALTO_LABEL_FLAME_VENTAS = 80
    ALTO_LABEL_FLAME_FORM = 40
# TreeView Tabla
    ALTO_TEEVIEW =400
# Widget Treeview
    ALTO_TEEVIEW_WIDGET= 40

# VENTAS
    ALTO_TRERFRAME_VENTAS=200
    ALTO_TEEVIEW_VENTAS = 10

    ALTO_LABEL_FLAME_INFERIOR=100
