from enum import Enum

class ANCHO (Enum):
    NORMAL_ANCHO = 1100

    ANCHO_CONTAINER = 400

    ANCHO_FRAME1 =100
    ANCHO_FRAME2 =  550
# BOTONES

    ANCHO_BOTON = 60
    ANCHO_BOTON_INVENTARIO = 240
    ANCHO_BOTON_VENTAS = 240

# LABEL
    ANCHO_LABEL_FLAME = 400
    ANCHO_LABEL_FLAME_VENTAS  = 1080
    ANCHO_LABEL_FLAME_FORM=240
# TreeView Tabla
    ANCHO_TEEVIEW = 620
# Widget Treeview
    ANCHO_TEEVIEW_NORMAL_WIDGET =70
    ANCHO_TEEVIEW_MEDIANO_WIDGET = 100
# entri
    ANCHO_VENTAS_ENTY= 150
    ANCHO_INVENTARIO_ENTY=80

# VENTAS
    ANCHO_TRERFRAME_VENTAS=800

    ANCHO_LABEL_FLAME_INFERIOR = 1060

